title: Portfolio for Catherine Yunis
description: A showcase of my engineering and artistic work
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cyunis.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  projects:
    output: true
    permalink: /projects/:path/

# Default front matter for projects
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
